development:
  adapter: postgresql
  encoding: unicode
  database: kayapinterest_development
  host: localhost
  pool: 5
  username: aria
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: kayapinterest_test
  host: localhost
  pool: 5
  username: aria
  password: 123456
